temp.txt: 
	echo "Hello test">temp.txt

%.c: %.l # cancels the implicit conversion of ass3_19CS10069_19CS30007.l to ass3_19CS10069_19CS30007.c using implicit make rules

%.c: %.y # cancels the implicit conversion of ass3_19CS10069_19CS30007.y to ass3_19CS10069_19CS30007.c using implicit make rules

clean:
	rm temp.txt